# Generated by Django 5.2.9 on 2025-12-14 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificación"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "type",
                    models.CharField(
                        choices=[("EXPENSE", "Gasto"), ("INCOME", "Ingreso")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, verbose_name="Categoría del sistema"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del ícono de Bootstrap Icons (ej: bi-cart)",
                        max_length=50,
                        null=True,
                        verbose_name="Ícono",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Color hexadecimal (ej: #28a745)",
                        max_length=7,
                        null=True,
                        verbose_name="Color",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["type", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "user", "type"),
                        name="unique_category_per_user_and_type",
                    )
                ],
            },
        ),
    ]
