# Generated by Django 5.2.9 on 2025-12-31 04:23

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="category",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                blank=True,
                default="#6c757d",
                help_text="Color hexadecimal (ej: #28a745)",
                max_length=7,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                default="bi-tag",
                help_text="Nombre del ícono de Bootstrap Icons (ej: bi-cart)",
                max_length=50,
                verbose_name="Ícono",
            ),
        ),
    ]
