# Generated by Django 5.2.9 on 2026-01-05 01:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_managers_alter_category_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["user", "type"], name="categories__user_id_135dec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_system", "type"], name="categories__is_syst_e25d55_idx"
            ),
        ),
    ]
