# Generated by Django 5.2.9 on 2026-02-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0004_seed_system_categories"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="category",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="category",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="category",
            name="is_active",
        ),
    ]
