# Generated by Django 5.2.9 on 2026-02-27 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "categories",
            "0005_alter_category_managers_remove_category_deleted_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_system", True), ("user__isnull", False), _negated=True
                ),
                name="system_category_no_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_system", False), ("user__isnull", True), _negated=True
                ),
                name="user_category_requires_user",
            ),
        ),
    ]
