# Generated by Django 5.2.9 on 2026-05-06 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0006_add_is_system_check_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Grupo al que pertenece esta subcategoría. Vacío = es un grupo.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcategories",
                to="categories.category",
                verbose_name="Grupo",
            ),
        ),
    ]
