# Generated by Django 5.2.9 on 2026-05-08 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0008_seed_system_groups_and_move_orphans"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="unique_category_per_user_and_type",
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("name", "user", "type"),
                name="unique_group_name_per_user_and_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("name", "user", "type", "parent"),
                name="unique_subcategory_name_per_user_type_and_parent",
            ),
        ),
    ]
