# Generated by Django 5.2.9 on 2026-05-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0009_fix_unique_constraint_include_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["type", "order", "name"],
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Posición del grupo en la lista (solo aplica a grupos).",
                verbose_name="Orden",
            ),
        ),
    ]
