# Generated by Django 5.2.9 on 2026-10-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0013_categoryoverride"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="monthly_alert_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Avisa cuando el gasto del mes en esta subcategoría supera este monto. Solo aplica a subcategorías de gasto.",
                max_digits=12,
                null=True,
                verbose_name="Umbral de alerta mensual",
            ),
        ),
    ]
