# Generated by Django 5.2.9 on 2026-05-30 17:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0011_simplify_system_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificación"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "expected_day",
                    models.PositiveSmallIntegerField(
                        help_text="Día del mes en que solés cobrar este ingreso (1-31).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Día esperado de cobro",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referencia opcional (ej: empresa, cliente).",
                        max_length=255,
                        verbose_name="Notas",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Categoría de ingreso a la que pertenece.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_incomes",
                        to="categories.category",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_incomes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingreso recurrente",
                "verbose_name_plural": "Ingresos recurrentes",
                "ordering": ["expected_day", "name"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="recurring_i_user_id_b55117_idx",
                    )
                ],
            },
        ),
    ]
