# Generated by Django 5.2.9 on 2026-05-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recurring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringexpense",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="Primer mes en que aplica este gasto (para el conteo de cuotas).",
                null=True,
                verbose_name="Mes de inicio",
            ),
        ),
        migrations.AddField(
            model_name="recurringexpense",
            name="total_installments",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Dejá vacío si el gasto no tiene fecha de fin (servicios, alquiler, etc.).",
                null=True,
                verbose_name="Cantidad de cuotas",
            ),
        ),
    ]
