# Generated by Django 5.2.9 on 2026-06-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recurring", "0002_add_installments_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringexpense",
            name="starting_installment",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Número de cuota desde la que empezás a registrar (por defecto 1).",
                null=True,
                verbose_name="Cuota de inicio",
            ),
        ),
    ]
