# Generated by Django 5.2.9 on 2026-10-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recurring", "0003_add_starting_installment"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringexpense",
            name="estimated_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monto tentativo mientras no se registró ningún pago real.",
                max_digits=12,
                null=True,
                verbose_name="Monto estimado",
            ),
        ),
    ]
