# Generated by Django 5.2.9 on 2026-10-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recurring", "0004_recurringexpense_estimated_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringexpense",
            name="is_auto_debit",
            field=models.BooleanField(
                default=False,
                help_text="Si se paga solo (débito automático), no se marca como vencido.",
                verbose_name="Débito automático",
            ),
        ),
    ]
