# Generated by Django 5.2.9 on 2026-05-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_seen_tour",
            field=models.BooleanField(default=False, verbose_name="Tour visto"),
        ),
    ]
