# Generated by Django 5.2.9 on 2026-05-31 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_has_seen_tour"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="financial_month_start_day",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Día del mes en que empieza tu período financiero (ej: día que cobrás el sueldo). Rango: 1-28.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(28),
                ],
                verbose_name="Inicio del mes financiero",
            ),
        ),
    ]
