# Generated by Django 5.2.9 on 2025-12-22 01:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Saving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificación"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nombre de la meta"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Monto objetivo",
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Monto actual",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("ARS", "Peso Argentino"),
                            ("USD", "Dólar Estadounidense"),
                        ],
                        default="ARS",
                        max_length=3,
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha objetivo"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activa"),
                            ("COMPLETED", "Completada"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-piggy-bank", max_length=50, verbose_name="Ícono"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#17a2b8", max_length=7, verbose_name="Color"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta de Ahorro",
                "verbose_name_plural": "Metas de Ahorro",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavingMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificación"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("DEPOSIT", "Depósito"), ("WITHDRAWAL", "Retiro")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Monto",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descripción"
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Fecha")),
                (
                    "saving",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="savings.saving",
                        verbose_name="Meta de ahorro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Ahorro",
                "verbose_name_plural": "Movimientos de Ahorro",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="saving",
            index=models.Index(
                fields=["user", "status"], name="savings_sav_user_id_f06e4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saving",
            index=models.Index(
                fields=["user", "is_active"], name="savings_sav_user_id_fb8576_idx"
            ),
        ),
    ]
