# Generated by Django 5.2.9 on 2026-01-05 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0002_alter_saving_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="saving",
            name="savings_sav_user_id_f06e4a_idx",
        ),
        migrations.RemoveIndex(
            model_name="saving",
            name="savings_sav_user_id_fb8576_idx",
        ),
        migrations.AddIndex(
            model_name="saving",
            index=models.Index(
                fields=["user", "status", "is_active"],
                name="savings_sav_user_id_fab529_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savingmovement",
            index=models.Index(
                fields=["saving", "-date", "-created_at"],
                name="savings_sav_saving__26dd3f_idx",
            ),
        ),
    ]
