# Generated by Django 5.2.9 on 2026-02-22 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0003_remove_saving_savings_sav_user_id_f06e4a_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="saving",
            managers=[],
        ),
        migrations.RemoveIndex(
            model_name="saving",
            name="savings_sav_user_id_fab529_idx",
        ),
        migrations.RemoveField(
            model_name="saving",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="saving",
            name="is_active",
        ),
        migrations.AddIndex(
            model_name="saving",
            index=models.Index(
                fields=["user", "status"], name="savings_sav_user_id_f06e4a_idx"
            ),
        ),
    ]
