# Generated by Django 5.2.9 on 2026-03-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0004_alter_saving_managers_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="savingmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="saving_movement_amount_positive",
            ),
        ),
    ]
