# Generated by Django 5.2.9 on 2026-03-03 03:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0005_add_check_constraint_movement_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="saving",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_amount__gt", 0)),
                name="saving_target_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="saving",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_amount__gte", 0)),
                name="saving_current_amount_non_negative",
            ),
        ),
    ]
