# Generated by Codex on 2026-03-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0006_saving_saving_target_amount_positive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saving",
            name="color",
            field=models.CharField(default="#28a745", max_length=7, verbose_name="Color"),
        ),
    ]
