# Generated by Django 5.2.9 on 2026-01-05 01:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0002_alter_budget_managers"),
        ("categories", "0002_alter_category_managers_alter_category_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="budget",
            name="budgets_bud_user_id_8e3844_idx",
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["user", "year", "month", "is_active"],
                name="budgets_bud_user_id_945f94_idx",
            ),
        ),
    ]
