# Generated by Django 5.2.9 on 2026-02-22 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0003_remove_budget_budgets_bud_user_id_8e3844_idx_and_more"),
        (
            "categories",
            "0005_alter_category_managers_remove_category_deleted_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="budget",
            managers=[],
        ),
        migrations.RemoveIndex(
            model_name="budget",
            name="budgets_bud_user_id_945f94_idx",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="is_active",
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["user", "year", "month"], name="budgets_bud_user_id_39ca25_idx"
            ),
        ),
    ]
