import 'package:flutter/material.dart';

const categoryIconChoices = <String>[
  'bi-cart',
  'bi-car-front',
  'bi-house',
  'bi-lightning',
  'bi-heart-pulse',
  'bi-controller',
  'bi-book',
  'bi-bag',
  'bi-cup-hot',
  'bi-basket',
  'bi-egg-fried',
  'bi-truck',
  'bi-fuel-pump',
  'bi-bus-front',
  'bi-airplane',
  'bi-phone',
  'bi-laptop',
  'bi-wifi',
  'bi-tv',
  'bi-music-note',
  'bi-film',
  'bi-bicycle',
  'bi-trophy',
  'bi-gift',
  'bi-people',
  'bi-person-heart',
  'bi-briefcase',
  'bi-cash',
  'bi-cash-coin',
  'bi-wallet2',
  'bi-bank',
  'bi-credit-card',
  'bi-piggy-bank',
  'bi-graph-up-arrow',
  'bi-shop',
  'bi-tools',
  'bi-house-gear',
  'bi-mortarboard',
  'bi-box-seam',
  'bi-stars',
  'bi-tag',
  'bi-three-dots',
];

const _categoryIconMap = <String, IconData>{
  'bi-cart': Icons.shopping_cart,
  'bi-car-front': Icons.directions_car,
  'bi-house': Icons.home,
  'bi-lightning': Icons.bolt,
  'bi-heart-pulse': Icons.favorite,
  'bi-controller': Icons.sports_esports,
  'bi-book': Icons.book,
  'bi-bag': Icons.shopping_bag,
  'bi-cup-hot': Icons.local_cafe,
  'bi-basket': Icons.shopping_basket,
  'bi-egg-fried': Icons.restaurant,
  'bi-truck': Icons.local_shipping,
  'bi-fuel-pump': Icons.local_gas_station,
  'bi-bus-front': Icons.directions_bus,
  'bi-airplane': Icons.flight,
  'bi-phone': Icons.phone,
  'bi-laptop': Icons.laptop,
  'bi-wifi': Icons.wifi,
  'bi-tv': Icons.tv,
  'bi-music-note': Icons.music_note,
  'bi-film': Icons.movie,
  'bi-bicycle': Icons.directions_bike,
  'bi-trophy': Icons.emoji_events,
  'bi-gift': Icons.card_giftcard,
  'bi-people': Icons.group,
  'bi-person-heart': Icons.volunteer_activism,
  'bi-briefcase': Icons.work,
  'bi-cash': Icons.payments,
  'bi-cash-coin': Icons.attach_money,
  'bi-wallet2': Icons.account_balance_wallet,
  'bi-bank': Icons.account_balance,
  'bi-credit-card': Icons.credit_card,
  'bi-piggy-bank': Icons.savings,
  'bi-graph-up-arrow': Icons.trending_up,
  'bi-shop': Icons.storefront,
  'bi-tools': Icons.build,
  'bi-house-gear': Icons.home_repair_service,
  'bi-mortarboard': Icons.school,
  'bi-box-seam': Icons.inventory_2,
  'bi-stars': Icons.stars,
  'bi-tag': Icons.label_outline,
  'bi-three-dots': Icons.more_horiz,
};

IconData categoryIconFromName(String name) =>
    _categoryIconMap[name] ?? Icons.label_outline;
