"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import config  # Averiguar

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# =============================================================================
# SECRET KEY
# =============================================================================

# En producción, SECRET_KEY DEBE estar configurada como variable de entorno
# En desarrollo, se permite un default para facilitar el setup inicial
SECRET_KEY = config("SECRET_KEY", default=None)

# Validación: Si no hay SECRET_KEY, mostrar error claro
if SECRET_KEY is None:
    raise ValueError(
        "\n" + "=" * 60 + "\n"
        "❌ ERROR: SECRET_KEY no está configurada\n" + "=" * 60 + "\n"
        "\n"
        "Opciones:\n"
        "1. Crear archivo .env con: SECRET_KEY=tu-clave-secreta\n"
        "2. Exportar variable: export SECRET_KEY=tu-clave-secreta\n"
        "\n"
        "Generar clave segura con:\n"
        '  python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"\n'
        "\n" + "=" * 60
    )

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG se define en dev.py o prod.py - NO en base.py
# Esto fuerza a cada entorno a definirlo explícitamente

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party
    "crispy_forms",
    "crispy_bootstrap5",
    "axes",
    # Local apps
    "apps.users",
    "apps.expenses",
    "apps.income",
    "apps.savings",
    "apps.budgets",
    "apps.reports",
    "apps.core",
    "apps.categories",
]

AUTH_USER_MODEL = "users.User"

# =============================================================================
# AUTENTICACIÓN
# =============================================================================

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",  # ← Primero axes
    "apps.users.backends.EmailOrUsernameModelBackend",
    "django.contrib.auth.backends.ModelBackend",  # ← Después el default
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "csp.middleware.CSPMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-ar"

TIME_ZONE = "America/Argentina/Buenos_Aires"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

LOGIN_REDIRECT_URL = "reports:dashboard"
LOGOUT_REDIRECT_URL = "users:login"
LOGIN_URL = "users:login"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =============================================================================
# DJANGO-AXES - Rate Limiting
# =============================================================================

# Número de intentos fallidos antes de bloquear
AXES_FAILURE_LIMIT = 5

# Tiempo de bloqueo en horas (None = hasta desbloqueo manual)
AXES_COOLOFF_TIME = 1  # 1 hora

# Qué considerar para el bloqueo
# 'ip_address' = solo IP
# 'username' = solo usuario
# 'ip_address,username' = combinación (más seguro)
AXES_LOCKOUT_PARAMETERS = ["ip_address", "username"]

# Reset de intentos después de login exitoso
AXES_RESET_ON_SUCCESS = True

# Habilitar logging
AXES_VERBOSE = True

# Ignorar URLs específicas (no aplicar rate limiting)
# AXES_NEVER_LOCKOUT_WHITELIST = True
# AXES_WHITELIST = ['admin']

# Guardar intentos en base de datos
AXES_ENABLE_ACCESS_FAILURE_LOG = True

# Mensaje personalizado (se mostrará en la página de lockout)
AXES_LOCKOUT_TEMPLATE = "users/account_locked.html"

# URL a redirigir cuando está bloqueado (alternativa al template)
# AXES_LOCKOUT_URL = '/cuenta-bloqueada/'

# Excluir IPs específicas del rate limiting (ej: tu IP de desarrollo)
# AXES_NEVER_LOCKOUT_GET = True  # No bloquear requests GET
# AXES_IP_WHITELIST = ['127.0.0.1']

# Para proxies/load balancers - obtener IP real del header
# AXES_PROXY_COUNT = 1
# AXES_META_PRECEDENCE_ORDER = ['HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR']


# =============================================================================
# LOGGING
# =============================================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    # Formateadores
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {module} {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "[{asctime}] {levelname} {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "security": {
            "format": "[{asctime}] {levelname} SECURITY {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    # Handlers (destinos de los logs)
    "handlers": {
        # Consola - para desarrollo
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        # Archivo general
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "app.log",
            "maxBytes": 5 * 1024 * 1024,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        # Archivo de errores
        "error_file": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "error.log",
            "maxBytes": 5 * 1024 * 1024,  # 5 MB
            "backupCount": 10,
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        # Archivo de seguridad
        "security_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "security.log",
            "maxBytes": 5 * 1024 * 1024,  # 5 MB
            "backupCount": 10,
            "formatter": "security",
            "encoding": "utf-8",
        },
    },
    # Loggers
    "loggers": {
        # Logger principal de Django
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        # Errores de Django
        "django.request": {
            "handlers": ["error_file", "console"],
            "level": "ERROR",
            "propagate": False,
        },
        # Seguridad de Django
        "django.security": {
            "handlers": ["security_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        # Django-axes (rate limiting)
        "axes": {
            "handlers": ["security_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        # Logger de nuestra aplicación
        "apps": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        # Logger de seguridad personalizado
        "security": {
            "handlers": ["security_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
