# Generated by Django 5.2.9 on 2025-12-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_alter_expense_amount_ars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="expense_type",
            field=models.CharField(
                blank=True,
                choices=[("FIXED", "Fijo"), ("VARIABLE", "Variable")],
                default="",
                max_length=10,
                verbose_name="Tipo de gasto",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASH", "Efectivo"),
                    ("DEBIT", "Tarjeta de Débito"),
                    ("CREDIT", "Tarjeta de Crédito"),
                    ("TRANSFER", "Transferencia"),
                ],
                default="",
                max_length=10,
                verbose_name="Método de pago",
            ),
        ),
    ]
