# Generated by Django 5.2.9 on 2025-12-31 04:23

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_alter_expense_expense_type_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="expense",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
