# Generated by Django 5.2.9 on 2026-01-05 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_managers_alter_category_color_and_more"),
        ("expenses", "0004_alter_expense_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="expense",
            name="expenses_ex_date_e4dd05_idx",
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["user", "is_active", "date"],
                name="expenses_ex_user_id_13cbfe_idx",
            ),
        ),
    ]
