# Generated by Django 5.2.9 on 2026-02-08 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_remove_expense_expenses_ex_date_e4dd05_idx_and_more"),
        ("savings", "0003_remove_saving_savings_sav_user_id_f06e4a_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="saving",
            field=models.ForeignKey(
                blank=True,
                help_text="Si se selecciona, este gasto se suma automáticamente al ahorro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_expenses",
                to="savings.saving",
                verbose_name="Destino de ahorro",
            ),
        ),
    ]
