# Generated by Django 5.2.9 on 2026-02-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0006_add_saving_link"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="expense",
            managers=[],
        ),
        migrations.RemoveIndex(
            model_name="expense",
            name="expenses_ex_user_id_13cbfe_idx",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="is_active",
        ),
    ]
