# Generated by Django 5.2.9 on 2026-02-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0007_alter_expense_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Descripción"
            ),
        ),
    ]
