# Generated by Django 5.2.9 on 2026-03-03 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0006_add_is_system_check_constraints"),
        ("expenses", "0008_allow_blank_description"),
        ("savings", "0006_saving_saving_target_amount_positive_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="expense_amount_positive"
            ),
        ),
    ]
