# Generated by Codex on 2026-03-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0010_fix_expense_related_name_plural"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS budgets_budget;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
