# Generated by Django 5.2.9 on 2026-05-10 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0011_drop_budget_table"),
        ("recurring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="recurring",
            field=models.ForeignKey(
                blank=True,
                help_text="Gasto recurrente al que corresponde este pago.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="recurring.recurringexpense",
                verbose_name="Gasto recurrente",
            ),
        ),
    ]
