# Generated by Django 5.2.9 on 2026-06-15 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0012_add_recurring_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="expense_type",
        ),
    ]
