# Generated by Django 5.2.9 on 2025-12-21 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificación"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("ARS", "Peso Argentino"),
                            ("USD", "Dólar Estadounidense"),
                        ],
                        default="ARS",
                        max_length=3,
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Tasa de cambio",
                    ),
                ),
                (
                    "amount_ars",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=14,
                        verbose_name="Monto en ARS",
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="Es recurrente"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incomes",
                        to="categories.category",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingreso",
                "verbose_name_plural": "Ingreso",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="income_inco_user_id_f74de7_idx"
                    ),
                    models.Index(
                        fields=["user", "category"],
                        name="income_inco_user_id_04ffe9_idx",
                    ),
                    models.Index(
                        fields=["date", "is_active"], name="income_inco_date_ec7c81_idx"
                    ),
                ],
            },
        ),
    ]
