# Generated by Django 5.2.9 on 2025-12-22 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="income",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Ingreso",
                "verbose_name_plural": "Ingresos",
            },
        ),
    ]
