# Generated by Django 5.2.9 on 2025-12-25 21:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0002_alter_income_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="amount_ars",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                max_digits=14,
                verbose_name="Monto en ARS",
            ),
        ),
    ]
