# Generated by Django 5.2.9 on 2025-12-31 04:23

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0003_alter_income_amount_ars"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="income",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
