# Generated by Django 5.2.9 on 2026-01-05 01:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_managers_alter_category_color_and_more"),
        ("income", "0004_alter_income_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="income",
            name="income_inco_date_ec7c81_idx",
        ),
        migrations.AddIndex(
            model_name="income",
            index=models.Index(
                fields=["user", "is_active", "date"],
                name="income_inco_user_id_880a2f_idx",
            ),
        ),
    ]
