# Generated by Django 5.2.9 on 2026-02-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0005_remove_income_income_inco_date_ec7c81_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="income",
            managers=[],
        ),
        migrations.RemoveIndex(
            model_name="income",
            name="income_inco_user_id_880a2f_idx",
        ),
        migrations.RemoveField(
            model_name="income",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="income",
            name="is_active",
        ),
    ]
