# Generated by Django 5.2.9 on 2026-03-01 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0006_alter_income_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="is_recurring",
        ),
    ]
