# Generated by Django 5.2.9 on 2026-03-03 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0006_add_is_system_check_constraints"),
        ("income", "0007_remove_is_recurring"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="income",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="income_amount_positive"
            ),
        ),
    ]
