# Generated by Django 5.2.9 on 2026-05-30 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0008_income_income_amount_positive"),
        ("recurring_income", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="recurring",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incomes",
                to="recurring_income.recurringincome",
                verbose_name="Ingreso recurrente",
            ),
        ),
    ]
