# Generated by Django 5.2.9 on 2026-10-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0009_add_recurring_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Descripción"
            ),
        ),
    ]
