# Generated by Django 5.2.9 on 2026-06-01 23:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0011_simplify_system_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseholdMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificación"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="household_members",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Miembro del hogar",
                "verbose_name_plural": "Miembros del hogar",
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="SharedExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificación"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("ARS", "Peso Argentino"),
                            ("USD", "Dólar Estadounidense"),
                        ],
                        default="ARS",
                        max_length=3,
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Tasa de cambio",
                    ),
                ),
                (
                    "amount_ars",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=14,
                        verbose_name="Monto en ARS",
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shared_expenses",
                        to="categories.category",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dejá vacío si pagaste vos.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paid_expenses",
                        to="shared_expenses.householdmember",
                        verbose_name="Pagado por",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto compartido",
                "verbose_name_plural": "Gastos compartidos",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="shared_expe_user_id_fbe875_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="shared_expense_amount_positive",
                    )
                ],
            },
        ),
    ]
